name: Check categories

on:
  pull_request:
    paths:
      - "plane-alert-db.csv"
      - "plane-alert-pia.csv"
      - "plane-alert-ukraine.csv"

jobs:
  checkCategories:
    runs-on: ubuntu-latest
    name: Check if main databases have valid Categories
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.10"
          cache: "pip"
      - run: pip install -r ./scripts/requirements.txt

      - name: Run main database checks
        run: python ./scripts/check_categories.py
