name: Create derivative databases

permissions:
  contents: write # Allow action to write back changes to repository.

on:
  push:
    branches: ["main"]
    paths:
      - "plane-alert-db.csv"
      - "plane-alert-ukraine.csv"
      - "plane_images.csv"
      - "scripts/create_db_derivatives.py"

jobs:
  createDerivativeDatabases:
    if: github.repository == 'sdr-enthusiasts/plane-alert-db' || ${{ vars.CREATE_DERIVATIVES }}
    name: Update derivative databases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.10"
          cache: "pip"
      - run: pip install -r ./scripts/requirements.txt

      - name: Update '/400/' paths to '/full/'
        run: python ./scripts/update_image_links.py

      - name: Create category and images derivative CSV files
        run: python ./scripts/create_db_derivatives.py

      - name: Create valid category listing
        run: python ./scripts/export_categories.py

      - name: Update README.md to include changes
        run: python ./scripts/update_readme.py

      - name: Commit derivative CSV files
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          commit_message: "refactor: update derivative databases."
