name: Label invalid PRs

on:
  workflow_run:
    workflows: ["Check derivatives change"]
    types:
      - completed

permissions:
  contents: read
  pull-requests: write

jobs:
  labelInvalidPRs:
    runs-on: ubuntu-latest
    name: Add warning if derivative change was detected
    if: github.event.workflow_run.event == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: check_derivatives_change
          workflow: check_derivatives_change.yml
          run_id: ${{github.event.workflow_run.id }}

      - name: Retrieve derivative check result from artifacts
        id: changed
        run: |
          issue_number=`cat issue_number`
          echo "issue_number=${issue_number}" >> "${GITHUB_OUTPUT}"

      - name: Add 'invalid' label if PR changes were wrong.
        if: github.event.workflow_run.conclusion == 'failure'
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['invalid']
            })
      - name: Remove 'invalid' label if PR changes were correct.
        if: github.event.workflow_run.conclusion == 'success'
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              name: 'invalid'
            })
